name: Act on release

on: 
  workflow_call:
    secrets:
      TELEGRAM_TO:
        required: true
      TELEGRAM_TOKEN:
        required: true
  workflow_dispatch:
      

jobs:
  Notify_Release:
    name: Notify Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # The python version to use.
          cache: 'pip'
          cache-dependency-path: 'telegram-script/requirements.txt'
        
      - name: Install dependencies
        run: pip install -r telegram-script/requirements.txt
     
      - name: Run telegram notification script
        run: python3 telegram-script

#     - name: Commit release description changes
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Update telegram release message ${{ github.run_id }}
#          branch: update
#          file_pattern: '*.md'
          
      - name: Telegram Channel Update
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message_file: release_notification.md
